<b>View:</b> <a href="<?php echo $this->base()->thisUrl(); ?>/home?tab=<?php echo $this->tab; ?>&from=twentyfour">24 Hours</a> |
<a href="<?php echo $this->base()->thisUrl(); ?>/home?tab=<?php echo $this->tab; ?>&from=week">Week</a> |
<a href="<?php echo $this->base()->thisUrl(); ?>/home?tab=<?php echo $this->tab; ?>&from=month">Month</a> |
<a href="<?php echo $this->base()->thisUrl(); ?>/home?tab=<?php echo $this->tab; ?>&from=year">Year</a> |
<a href="<?php echo $this->base()->thisUrl(); ?>/home?tab=<?php echo $this->tab; ?>&from=all">All Time</a>

<h2>In the last <?php echo $this->interval_name; ?>...</h2>
<?php if( false === $this->items ): ?>
	<p>I have done nothing. Please check my pulse.</p>
<?php else: ?>
	<p>I've posted <?php echo $this->total; ?> bits of text, links, videos and photos.</p>
	
	<p>The most recent was from <?php echo $this->latest_ago; ?> ago, it was from <?php echo $this->latest_source; ?></p>
	
	<div id="latest-item" style="background: #DFDFDF; padding: 5px;">
		<?php
			echo $this->partial(
				'timeline/item.phtml',
				'public',
				array(
					'item' => $this->latest,
					'admin' => $this->admin,
					'model' => $this->models[ $this->latest->getSource() ],
					'disqus' => $this->disqus,
					'googlefc' => $this->googlefc
				)
			); 
		?>
	</div>
	
	<h2>Posts By Type</h2>
	<div class="thing-ive-done" style="text-align: center;">
		<?php print '<img src="' . $this->type_distribution_url . '" alt="Loading..." />'; ?>
	</div>
	
	<h2>Posts By Source</h2>
	<div class="thing-ive-done" style="text-align: center;">
		<?php print '<img src="' . $this->source_distribution_url . '" alt="Loading..." />'; ?>
	</div>
	
	<h2><?php echo $this->total_by_interval; ?></h2>
	<div class="thing-ive-done" style="text-align: center;">
		<?php print '<img src="' . $this->total_by_interval_url . '" alt="Loading..." />'; ?>
	</div>
<?php endif; ?>
